// Generated by https://quicktype.io

export interface Pedido {
  cliente:      Cliente;
  fechaEntrega: string;
  lugarEntrega: string;
  articulos:    Articulo[];
  total:        number;
  estatus:      Estatus;
  id:           string;
}

export interface Articulo {
  articulo: null;
  cantidad: number;
  _id:      string;
}

export interface Cliente {
  _id:    string;
  nombre: string;
}

export interface Estatus {
  _id:  string;
  desc: string;
}

export interface PedidoSignal {
  loading: boolean,
  pedidos: Pedido[]
}
