
export interface PedidoSignal {
  loading: boolean,
  pedidos: Pedido[]
}

// Generated by https://quicktype.io

export interface Pedido {
  cliente:      Cliente;
  fechaEntrega: string;
  lugarEntrega: string;
  items:        Items;
  total:        number;
  estatus:      Estatus;
  id:           string;
}

export interface Cliente {
  _id:    string;
  nombre: string;
}

export interface Estatus {
  _id:  string;
  desc: string;
}

export interface Items {
  articulo: Articulo;
  cantidad: number;
}

export interface Articulo {
  _id: string;
  nombre: string;
}

