// Generated by https://quicktype.io

import { Producto } from "./producto.interface";

export interface Precio {
  articulo:     string;
  producto:     Producto;
  cantidad:     number;
  fecha_compra: string;
  id:           string;
}


